import PDFDocument from "pdfkit";
import fs from "node:fs";
import path from "node:path";
import { formatINR } from "./money";
import { formatDisplayDate } from "./dates";

const COPPER = "#C06618";
const BLACK = "#111111";
const GREY = "#5A5A5A";

function fontPath(file: string) {
  return path.join(/* turbopackIgnore: true */ process.cwd(), "public/fonts", file);
}

function logoPath() {
  return path.join(/* turbopackIgnore: true */ process.cwd(), "public/brand/logo-white.png");
}

function createDoc(size: "A4" | "A5", margin: number) {
  return new PDFDocument({
    size,
    margin,
    font: fontPath("NotoSans-Regular.ttf"),
  });
}

type PdfDoc = InstanceType<typeof PDFDocument>;

function useBold(doc: PdfDoc) {
  return doc.font(fontPath("NotoSans-Bold.ttf"));
}

function useRegular(doc: PdfDoc) {
  return doc.font(fontPath("NotoSans-Regular.ttf"));
}

type ReportRow = {
  date: string;
  receiptNo: string;
  employeeCode: string;
  employeeName: string;
  amount: number;
  remaining: number;
  issuedBy: string;
  note?: string | null;
};

export type PdfReportInput = {
  companyName: string;
  title: string;
  periodLabel: string;
  generatedBy: string;
  totalAmount: number;
  totalRemaining: number;
  rows: ReportRow[];
};

export function buildUpadReportPdf(input: PdfReportInput): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = createDoc("A4", 42);
    const chunks: Buffer[] = [];
    doc.on("data", (c) => chunks.push(c as Buffer));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.rect(0, 0, doc.page.width, 72).fill(BLACK);
    const logo = logoPath();
    if (fs.existsSync(logo)) {
      try {
        doc.image(logo, 42, 12, { height: 48 });
        useBold(doc).fillColor(COPPER).fontSize(16).text(input.companyName.toUpperCase(), 110, 22);
        useRegular(doc).fillColor("#FFFFFF").fontSize(10).text("ASM  ·  Advance Salary Manager", 110, 44);
      } catch {
        useBold(doc).fillColor(COPPER).fontSize(16).text(input.companyName.toUpperCase(), 42, 22);
        useRegular(doc).fillColor("#FFFFFF").fontSize(10).text("ASM  ·  Advance Salary Manager", 42, 44);
      }
    } else {
      useBold(doc).fillColor(COPPER).fontSize(16).text(input.companyName.toUpperCase(), 42, 22);
      useRegular(doc).fillColor("#FFFFFF").fontSize(10).text("ASM  ·  Advance Salary Manager", 42, 44);
    }

    useBold(doc).fillColor(BLACK).fontSize(18).text(input.title, 42, 96);
    useRegular(doc).fillColor(GREY).fontSize(11).text(input.periodLabel, 42, 122);
    doc.text(`Generated by ${input.generatedBy}  ·  ${formatDisplayDate(new Date())}`, 42, 138);

    doc.roundedRect(42, 160, 240, 54, 6).fill("#F7F1EA");
    doc.roundedRect(298, 160, 255, 54, 6).fill("#F7F1EA");
    useRegular(doc).fillColor(COPPER).fontSize(9).text("TOTAL UPAD IN PERIOD", 54, 170);
    useBold(doc).fillColor(BLACK).fontSize(16).text(formatINR(input.totalAmount), 54, 186);
    useRegular(doc).fillColor(COPPER).fontSize(9).text("STILL OUTSTANDING FROM THESE", 310, 170);
    useBold(doc).fillColor(BLACK).fontSize(16).text(formatINR(input.totalRemaining), 310, 186);

    const startY = 234;
    const cols = [
      { label: "Date", x: 42, w: 70 },
      { label: "Receipt", x: 112, w: 90 },
      { label: "Emp", x: 202, w: 58 },
      { label: "Name", x: 260, w: 110 },
      { label: "Amount", x: 370, w: 70 },
      { label: "Balance", x: 440, w: 70 },
      { label: "By", x: 510, w: 44 },
    ];

    doc.rect(42, startY, 511, 22).fill(BLACK);
    useBold(doc).fillColor("#FFFFFF").fontSize(8);
    cols.forEach((c) => doc.text(c.label, c.x, startY + 7, { width: c.w }));

    let y = startY + 22;
    useRegular(doc).fontSize(8);
    input.rows.forEach((row, i) => {
      if (y > 760) {
        doc.addPage();
        y = 48;
      }
      if (i % 2 === 0) {
        doc.rect(42, y, 511, 18).fill("#FBF7F2");
      }
      doc.fillColor(BLACK);
      doc.text(row.date, 42, y + 5, { width: 70 });
      doc.text(row.receiptNo, 112, y + 5, { width: 90 });
      doc.text(row.employeeCode, 202, y + 5, { width: 58 });
      doc.text(row.employeeName, 260, y + 5, { width: 110 });
      doc.text(formatINR(row.amount), 370, y + 5, { width: 70, align: "right" });
      doc.text(formatINR(row.remaining), 440, y + 5, { width: 70, align: "right" });
      doc.text(row.issuedBy, 510, y + 5, { width: 44 });
      y += 18;
    });

    if (input.rows.length === 0) {
      doc.fillColor(GREY).fontSize(11).text("No upad entries in this period.", 42, y + 16);
    }

    doc.fillColor(GREY).fontSize(8).text(
      "Vision 360  ·  Confidential staff record  ·  PIN confirmation replaces diary signature",
      42,
      800,
      { align: "center", width: 511 },
    );
    doc.end();
  });
}

export type ReceiptPdfInput = {
  companyName: string;
  kind: "UPAD" | "SALARY";
  receiptNo: string;
  employeeName: string;
  employeeCode: string;
  amount: number;
  extraLines: { label: string; value: string }[];
  confirmedBy: string;
};

export function buildReceiptPdf(input: ReceiptPdfInput): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = createDoc("A5", 36);
    const chunks: Buffer[] = [];
    doc.on("data", (c) => chunks.push(c as Buffer));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.rect(0, 0, doc.page.width, 64).fill(BLACK);
    useBold(doc).fillColor(COPPER).fontSize(14).text(input.companyName.toUpperCase(), 36, 20);
    useRegular(doc).fillColor("#FFFFFF").fontSize(9).text(
      input.kind === "UPAD" ? "UPAD RECEIPT  ·  PIN CONFIRMED" : "SALARY PAYOUT RECEIPT",
      36,
      40,
    );

    useRegular(doc).fillColor(GREY).fontSize(9).text("Receipt no.", 36, 88);
    useBold(doc).fillColor(BLACK).fontSize(13).text(input.receiptNo, 36, 102);
    useRegular(doc).fillColor(GREY).fontSize(9).text("Date", 240, 88);
    useBold(doc).fillColor(BLACK).fontSize(11).text(formatDisplayDate(new Date()), 240, 102);

    doc.moveTo(36, 128).lineTo(380, 128).strokeColor("#E6D5C3").stroke();
    useRegular(doc).fillColor(GREY).fontSize(9).text("Employee", 36, 142);
    useBold(doc).fillColor(BLACK).fontSize(14).text(input.employeeName, 36, 156);
    useRegular(doc).fillColor(GREY).fontSize(9).text(input.employeeCode, 36, 176);

    doc.roundedRect(36, 204, 344, 64, 8).fill("#F7F1EA");
    useRegular(doc).fillColor(COPPER).fontSize(9).text(
      input.kind === "UPAD" ? "AMOUNT RECEIVED" : "CASH PAID",
      48,
      216,
    );
    useBold(doc).fillColor(BLACK).fontSize(22).text(formatINR(input.amount), 48, 232);

    let y = 286;
    input.extraLines.forEach((line) => {
      useRegular(doc).fillColor(GREY).fontSize(9).text(line.label, 36, y);
      useBold(doc).fillColor(BLACK).fontSize(10).text(line.value, 180, y, { width: 200, align: "right" });
      y += 18;
    });

    useRegular(doc).fillColor(GREY).fontSize(8).text(
      `Confirmed with employee 4-digit PIN  ·  Issued by ${input.confirmedBy}`,
      36,
      460,
      { width: 344, align: "center" },
    );
    doc.end();
  });
}
