<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Company>V360 Technetronic LLP</Company>
    <Product>Diamond File Router</Product>
    <Authors>VISION 360°</Authors>
    <Copyright>© V360 Technetronic LLP. Internal use only.</Copyright>
    <Version>1.1.0</Version>
    <AssemblyVersion>1.1.0.0</AssemblyVersion>
    <FileVersion>1.1.0.0</FileVersion>
    <NeutralLanguage>en-US</NeutralLanguage>
    <Deterministic>true</Deterministic>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
</Project>
